App\Entity\Project:
    attributes:
        id:
            groups: ["project", "projectUpdate"]
        name:
            groups: ["project", "projectUpdate"]
        color:
            groups: ["project", "projectUpdate"]
        description:
            groups: ["project", "projectUpdate"]
        taskCount:
            groups: ["project"]
