App\Entity\Project:
    attributes:
        id:
            groups: ["project"]
        name:
            groups: ["project"]
        color:
            groups: ["project"]
        taskCount:
            groups: ["project"]
